import numpy as np
from scipy import signal
from plot_zplane import zplane
from matplotlib import pyplot as plt
b = np.array([0.0018,0.0073,0.011,0.007,0.008])
a = np.array([1,-3.0544,3.8291,-2.2925,0.55072])
zeros, poles, gain= signal.tf2zpk(b,a)
sos=signal.tf2sos(b,a)
z1,p1,g1=signal.tf2zpk(sos[0,0:3],sos[0,3:6])
z2,p2,g2=signal.tf2zpk(sos[1,0:3],sos[1,3:6])
print(z1, p1)
w, h = signal.freqz(b, a)
fig=plt.figure(constrained_layout=True,figsize=(11.69,8.27))
(subfig1, subfig2)=fig.subfigures(1,2,wspace=0.05,width_ratios=[1,4])
subfig1.suptitle('Pole and zero plot')
(axleft1,axleft2,axleft3)=subfig1.subplots(3,1)
zplane(zeros,poles,axleft1)
axleft1.set_title('System')
axleft1.set_ylabel('Imaginary part')
axleft1.set_xlabel('Real part')
zplane(z1,p1,axleft2)
axleft2.set_title('1st SOS')
axleft2.set_ylabel('Imaginary part')
axleft2.set_xlabel('Real part')
zplane(z2,p2,axleft3)
axleft3.set_title('2nd SOS')
axleft3.set_ylabel('Imaginary part')
axleft3.set_xlabel('Real part')
axRight=subfig2.subplots(1,1)
axRight.plot(w/np.pi,abs(h))
axRight.grid()
axRight.set_title('Linearized form')
axRight.set_ylabel('Gain')
axRight.set_xlabel('Normalized Frequency ($\\times \pi$ rad/sample)')
fig.suptitle('Frequency Response of the system\n(PUL074BEX007)',fontsize='xx-large')
plt.show()

