prompt = 'Enter the modulation index\n';
m = input(prompt);
t=linspace(0,0.1,10000);
Am=5;
fm=37.7;
fc=48000;
ym=Am*cos(2*pi*fm*t);
Ac=Am/m;
yc=Ac*cos(2*pi*fc*t);
yam=Ac*(1+m*cos(2*pi*fm*t)).*cos(2*pi*fc*t);
[u, l]=envelope(yam);
temp= yam.*yc;
ydm=conv(temp, exp(-t/0.0009));

subplot(4,1,1);
plot(t,ym);
grid on;
title('Modulating Signal');
xlabel('Time (Sec)');
ylabel ('Amplitude (Volt)');
subplot(4,1,2);
plot(t,yc);
grid on;
title('Carrier Signal');
xlabel('Time (Sec)');
ylabel('Amplitude (Volt)');
subplot(4,1,3);
plot(t,yam);
hold on;
plot(t,u,'r');
plot(t,l,'g--');
grid on;
title('Amplitude Modulated Signal');
xlabel('Time(Sec)');
ylabel('Amplitude (Volt)');
subplot(4,1,4);
plot(t(1:10000),ydm(1:10000));
grid on;
title('Demodulated Signal');
xlabel('Time(Sec)');
ylabel('Amplitude (Volt)');